/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game.JPanels;

import Game.Frames.GameWindow;
import Avatars.Direction;
import Avatars.Human;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author kamil_2
 */
public class City extends PartOfMap{
    
    /**
     * Creates new form City
     */
    public City() {
        super();
        Human citizen = new Human(new Dimension(1000, 700));
        citizen.setPosition(800, 200);
        getAvatarsOnMap().add(citizen);
    }
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g, new Color(100, 180, 0));
        Graphics2D g2d = (Graphics2D) g;
        drawBorders(g2d, false, false, true, false);
        g2d.dispose();
    }
    @Override
    public PartOfMap getPlaceBehindDoors(Direction doors) {
        if(System.currentTimeMillis() - getLastDoorsUsage() < getDoorsCD())
            return null;
        setLastDoorsUsage(System.currentTimeMillis());
        switch(doors){
            case RIGHT: 
                GameWindow.myHero.setPosition(0, getSize().height/2);
                return (PartOfMap) GameWindow.getArena();
            default:
                return null;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents




    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
